FROM harishanand95/pushpin
MAINTAINER Harish Anand "https://github.com/harishanand95"

COPY config/kong/pushpin.conf /root/pushpin/pushpin.conf
COPY config/kong/pushpin_routes /root/pushpin/routes
COPY config/kong/default_443.key /root/pushpin/runner/certs/default_443.key
COPY config/kong/default_443.crt /root/pushpin/runner/certs/default_443.crt


EXPOSE 443
WORKDIR /root/pushpin

CMD    ["pushpin"]
