---
  - name: Start mongodb service
    command: service mongod start
    become: yes
    become_user: root

  - name: Start catalogue server
    shell: cd /home/ansible/cat-json-schema-server && screen -dm npm start
    become: yes
    become_user: root