---
  - name: Start logstash
    service: name=logstash state=started
    become: yes
    become_user: root

  - name: Start elasticsearch
    service: name=elasticsearch state=started
    become: yes
    become_user: root

  - name: Start kibana
    service: name=kibana state=started
    become: yes
    become_user: root

